version: '3.9'

services:
  db:
    container_name: database
    image: postgres
    env_file:
      - ".env"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    volumes:
      - .:/src
    restart: always
    ports:
      - "32080:80"
    env_file:
      - ".env"
    depends_on:
      - db